Fix build error due to missing #include
Error was:

  search.cpp:167:9: error: ‘sort’ was not declared in this scope; did you mean ‘short’?
    167 |         sort(results.begin(), results.end());
        |         ^~~~
        |         short