Fix build error due to static assert
Error was:

 ../conffile.cpp:395:19:   required from here
  /usr/include/c++/11/bits/stl_tree.h:770:15: error: static assertion failed: comparison object must be invocable as const
    770 |               is_invocable_v<const _Compare&, const _Key&, const _Key&>,
        |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~